#!/usr/bin/env python
import sys
import os
import os.path
from unittest import TestLoader, TextTestRunner
from friskby import SDS011

TEST_PYTHONPATH = "%s:%s" % (os.path.abspath(os.path.join(os.path.dirname(__file__), "../lib")),
                             os.path.abspath(os.path.dirname(__file__)))

os.environ["PYTHONPATH"] = TEST_PYTHONPATH + os.pathsep + os.getenv("PYTHONPATH", "")
for path_element in reversed(TEST_PYTHONPATH.split(os.pathsep)):
    sys.path.insert(0, path_element)


if SDS011.is_mock():
    os.environ["FRISKBY_TEST"] = "True"


def findTestsInDirectory(path, recursive=True, pattern="test*.py"):
    loader = TestLoader()
    test_suite = loader.discover(path, pattern=pattern)

    for (root, dirnames, _) in os.walk(path):
        for directory in dirnames:
            test_suite.addTests(findTestsInDirectory(os.path.join(root, directory),
                                                     recursive, pattern))

    return test_suite


TEST_SUITE = findTestsInDirectory(os.path.dirname(__file__))
TEST_RUNNER = TextTestRunner(verbosity=1)
TEST_RUNNER.run(TEST_SUITE)
if not TEST_RUNNER.run(TEST_SUITE).wasSuccessful():
    sys.exit('RPiParticle test failed!')
