#!/usr/bin/env python
import sys
import os
import os.path
from unittest import TestLoader, TextTestRunner
from friskby import SDS011

if SDS011.is_mock():
    os.environ["FRISKBY_TEST"] = "True"

def find_tests(path, recursive=True, pattern="test*.py"):
    loader = TestLoader()
    test_suite = loader.discover(path, pattern=pattern)

    for (root, dirnames, _) in os.walk(path):
        for directory in dirnames:
            test_suite.addTests(find_tests(os.path.join(root, directory),
                                           recursive, pattern))

    return test_suite

def run_tests():
    test_suite = find_tests(os.path.dirname(__file__))
    test_runner = TextTestRunner(verbosity=1)
    test_run = test_runner.run(test_suite)
    return test_run.wasSuccessful()

if __name__ == '__main__':
    SUCCESS = run_tests()
    if not SUCCESS:
        sys.exit('RPiParticle test failed!')
