#!/usr/bin/env python
"""The friskby manager, checks if there is a new update in git and in the friskby
cloud.

"""

from __future__ import (print_function, absolute_import)
import os
from friskby import FriskbyManager, DeviceConfig
from rpiparticle import fby_settings

if __name__ == "__main__":
    CONFIG_FILE = fby_settings.get_setting("rpi_config_path")
    DEV_CFG = DeviceConfig(CONFIG_FILE)
    FBY = FriskbyManager(DEV_CFG)
    FBY.run()
