#!/usr/bin/env python
"""An executable that submits unsubmitted data from sql to the friskby cloud.

Marks uploaded data in dao as such.

"""
from __future__ import print_function
import sys
from friskby import FriskbySubmitter, FriskbyDao
from rpiparticle import fby_settings

if __name__ == '__main__':
    settings = fby_settings.get_settings()
    rpi_db = settings['rpi_db']
    device_config_path = settings['rpi_config_path']
    if len(sys.argv) > 1:
        rpi_db = sys.argv[1]

    DAO = FriskbyDao(rpi_db)
    SUB = FriskbySubmitter(DAO, device_config_path)
    SUB.post()
