#!/usr/bin/env python
"""The old runner, checks if there is a new update in git and in the friskby
cloud.

"""

from __future__ import (print_function, absolute_import)
import os
from friskby import FriskbyRunner
from rpiparticle import fby_settings

if __name__ == "__main__":
    ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "../"))
    CONFIG_FILE = fby_settings.get_setting("rpi_config_path")
    VAR_PATH = os.path.join(ROOT, "var")

    FBY = FriskbyRunner(root=ROOT, config_file=CONFIG_FILE, var_path=VAR_PATH)
    FBY.run()
