#!/usr/bin/env python
from __future__ import (print_function, absolute_import)
import os.path
from friskby import DeviceConfig

default_root_url = "https://friskby.herokuapp.com"
sensor_path = "/sensor/api/device"
default_ROOT = "/usr/local/friskby"


while True:
    device_id = raw_input("Device id....: ")
    root_url = raw_input("Root url for server (default: %s) .." % default_root_url)
    if root_url == "":
        root_url = default_root_url

    ROOT = raw_input("Installation root (default: %s) .." % default_ROOT)
    if ROOT == "":
        ROOT = default_ROOT
    print()

    config_url = root_url + "%s/%s/" % (sensor_path, device_id)
    print("Fetching config from:%s [NB: Make sure to unlock the %s device.] " %
          (config_url, device_id))

    try:
        config = DeviceConfig.download(config_url)
        break
    except Exception as e:
        print("Failed to download configuration: %s - need to (re)open device on server?\n" % e)

config.save(filename=os.path.join(ROOT, "etc/config.json"))
